# Generated by Django 5.2 on 2025-05-04 12:16

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_creation', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('permissions', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='Audit_Numerique.cooperative')),
            ],
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_adhesion', models.DateField(default=django.utils.timezone.now)),
                ('actif', models.BooleanField(default=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='Audit_Numerique.cooperative')),
            ],
        ),
        migrations.CreateModel(
            name='Cotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('reguliere', 'Régulière'), ('exceptionnelle', 'Exceptionnelle'), ('solidarite', 'Solidarité')], default='reguliere', max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=20)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotisations', to='Audit_Numerique.membre')),
            ],
        ),
        migrations.CreateModel(
            name='Pret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taux_interet', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('date_demande', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_approbation', models.DateTimeField(blank=True, null=True)),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('demande', 'Demandé'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté'), ('en_cours', 'En cours'), ('rembourse', 'Remboursé'), ('en_retard', 'En retard')], default='demande', max_length=20)),
                ('motif', models.TextField()),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prets', to='Audit_Numerique.membre')),
            ],
        ),
        migrations.CreateModel(
            name='Remboursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateTimeField(default=django.utils.timezone.now)),
                ('methode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('mobile_money', 'Mobile Money'), ('virement', 'Virement bancaire'), ('autre', 'Autre')], default='especes', max_length=20)),
                ('pret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remboursements', to='Audit_Numerique.pret')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('cotisation', 'Cotisation'), ('pret', 'Prêt'), ('remboursement', 'Remboursement'), ('autre', 'Autre')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_transaction', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='Audit_Numerique.membre')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('date_inscription', models.DateTimeField(default=django.utils.timezone.now)),
                ('actif', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='audit_utilisateur_set', related_query_name='audit_utilisateur', to='auth.group', verbose_name='groups')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs_ayant_ce_role', to='Audit_Numerique.role')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='audit_utilisateur_permissions_set', related_query_name='audit_utilisateur_permission', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('cotisation', 'Cotisation'), ('pret', 'Prêt'), ('remboursement', 'Remboursement'), ('systeme', 'Système'), ('autre', 'Autre')], max_length=20)),
                ('contenu', models.TextField()),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('lue', models.BooleanField(default=False)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Audit_Numerique.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateTimeField(default=django.utils.timezone.now)),
                ('lu', models.BooleanField(default=False)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to='Audit_Numerique.utilisateur')),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to='Audit_Numerique.utilisateur')),
            ],
        ),
        migrations.AddField(
            model_name='membre',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adhesions', to='Audit_Numerique.utilisateur'),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cooperatives_administrees', to='Audit_Numerique.utilisateur'),
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('financier', 'Financier'), ('securite', 'Sécurité'), ('systeme', 'Système'), ('utilisateur', 'Utilisateur')], max_length=20)),
                ('description', models.TextField()),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('details', models.JSONField(default=dict)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to='Audit_Numerique.utilisateur')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='membre',
            unique_together={('utilisateur', 'cooperative')},
        ),
    ]
