# Generated by Django 5.2.5 on 2025-08-19 21:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Audit_Numerique", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cooperative",
            name="date_creation",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="evenement",
            name="date_debut",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="evenement",
            name="date_fin",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="membre",
            name="date_adhesion",
            field=models.DateField(auto_now_add=True),
        ),
    ]
